<a href="https://colab.research.google.com/github/DemonWillCode/Demo-Dashboard/blob/main/Model%20trained%20through%20collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Libraries and Dependencies

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

Importing Scikit-learn Libraries

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Data Manipulation

In [ ]:
data = pd.read_csv('Mumbai.csv')
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7719 entries, 0 to 7718
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Price                7719 non-null   int64
 1   Area                 7719 non-null   int64
 2   Location             7719 non-null   object
 3   No. of Bedrooms      7719 non-null   int64
 4   Resale               7719 non-null   int64
 5   MaintenanceStaff     7719 non-null   int64
 6   Gymnasium            7719 non-null   int64
 7   SwimmingPool         7719 non-null   int64
 8   LandscapedGardens    7719 non-null   int64
 9   JoggingTrack         7719 non-null   int64
 10  RainWaterHarvesting  7719 non-null   int64
 11  IndoorGames          7719 non-null   int64
 12  ShoppingMall         7719 non-null   int64
 13  Intercom             7719 non-null   int64
 14  SportsFacility       7719 non-null   int64
 15  ATM                  7719 non-null   int64
 16  ClubHouse            7719 non-null   int64
 17  School               7719 non-null   int64
 18  24X7Security         7719 non-null   int64
 19  PowerBackup          7719 non-null   int64
 20  CarParking           7719 non-null   int64
 21  StaffQuarter         7719 non-null   int64
 22  Cafeteria            7719 non-null   int64
 23  MultipurposeRoom     7719 non-null   int64
 24  Hospital             7719 non-null   int64
 25  WashingMachine       7719 non-null   int64
 26  Gasconnection        7719 non-null   int64
 27  AC                   7719 non-null   int64
 28  Wifi                 7719 non-null   int64
 29  Children'splayarea   7719 non-null   int64
 30  LiftAvailable        7719 non-null   int64
 31  BED                  7719 non-null   int64
 32  VaastuCompliant      7719 non-null   int64
 33  Microwave            7719 non-null   int64
 34  GolfCourse           7719 non-null   int64
 35  TV                   7719 non-null   int64
 36  DiningTable          7719 non-null   int64
 37  Sofa                 7719 non-null   int64
 38  Wardrobe             7719 non-null   int64
 39  Refrigerator         7719 non-null   int64
dtypes: int64(39), object(1)
memory usage: 2.4+ MB

In [ ]:
data.dropna(inplace=True)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7719 entries, 0 to 7718
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Price                7719 non-null   int64
 1   Area                 7719 non-null   int64
 2   Location             7719 non-null   object
 3   No. of Bedrooms      7719 non-null   int64
 4   Resale               7719 non-null   int64
 5   MaintenanceStaff     7719 non-null   int64
 6   Gymnasium            7719 non-null   int64
 7   SwimmingPool         7719 non-null   int64
 8   LandscapedGardens    7719 non-null   int64
 9   JoggingTrack         7719 non-null   int64
 10  RainWaterHarvesting  7719 non-null   int64
 11  IndoorGames          7719 non-null   int64
 12  ShoppingMall         7719 non-null   int64
 13  Intercom             7719 non-null   int64
 14  SportsFacility       7719 non-null   int64
 15  ATM                  7719 non-null   int64
 16  ClubHouse            7719 non-null   int64
 17  School               7719 non-null   int64
 18  24X7Security         7719 non-null   int64
 19  PowerBackup          7719 non-null   int64
 20  CarParking           7719 non-null   int64
 21  StaffQuarter         7719 non-null   int64
 22  Cafeteria            7719 non-null   int64
 23  MultipurposeRoom     7719 non-null   int64
 24  Hospital             7719 non-null   int64
 25  WashingMachine       7719 non-null   int64
 26  Gasconnection        7719 non-null   int64
 27  AC                   7719 non-null   int64
 28  Wifi                 7719 non-null   int64
 29  Children'splayarea   7719 non-null   int64
 30  LiftAvailable        7719 non-null   int64
 31  BED                  7719 non-null   int64
 32  VaastuCompliant      7719 non-null   int64
 33  Microwave            7719 non-null   int64
 34  GolfCourse           7719 non-null   int64
 35  TV                   7719 non-null   int64
 36  DiningTable          7719 non-null   int64
 37  Sofa                 7719 non-null   int64
 38  Wardrobe             7719 non-null   int64
 39  Refrigerator         7719 non-null   int64
dtypes: int64(39), object(1)
memory usage: 2.4+ MB

In [ ]:
X = data.drop(['Price'], axis=1)
y = data['Price']
X = pd.get_dummies(X, columns=['Location'], drop_first=True)
X

,Area,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,RainWaterHarvesting,IndoorGames,...,Location_royal palms goregaon east,Location_sec 50 new,Location_taloja panchanand,Location_thakur village kandivali east,Location_ulhasnagar 4,Location_vasant vihar thane west,Location_vile parle west,Location_vrindavan society,Location_worli sea Fase,Location_worli sea face
0,720,1,1,1,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,600,1,1,1,1,1,0,1,1,0,...,False,False,False,False,False,False,False,False,False,False
2,650,1,1,1,1,1,0,1,1,0,...,False,False,False,False,False,False,False,False,False,False
3,650,1,1,1,0,0,1,0,1,0,...,False,False,False,False,False,False,False,False,False,False
4,665,1,1,1,0,0,1,0,1,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7714,1180,2,0,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,False
7715,530,1,1,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,False
7716,700,1,0,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,False
7717,995,2,0,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,False
7718,1020,2,0,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
train_data = (X_train.join(y_train))
train_data

,Area,No. of Bedrooms,Resale,MaintenanceStaff,Gymnasium,SwimmingPool,LandscapedGardens,JoggingTrack,RainWaterHarvesting,IndoorGames,...,Location_sec 50 new,Location_taloja panchanand,Location_thakur village kandivali east,Location_ulhasnagar 4,Location_vasant vihar thane west,Location_vile parle west,Location_vrindavan society,Location_worli sea Fase,Location_worli sea face,Price
1817,1100,2,1,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,10000000
4298,900,2,1,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,12500000
836,820,2,1,0,1,1,1,1,1,1,...,False,False,False,False,False,False,False,False,False,8000000
1145,657,1,1,0,1,1,1,1,0,0,...,False,False,False,False,False,False,False,False,False,7200000
6433,1350,2,1,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,4800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4127,510,1,1,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,12600000
3856,625,1,1,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,18000000
6020,1250,2,0,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,32000000
795,1100,3,1,1,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,False,19100000
6983,550,1,0,9,9,9,9,9,9,9,...,False,False,False,False,False,False,False,False,False,74500000

Building the Linear Regression Model

In [ ]:
X_train, y_train = train_data.drop(['Price'], axis=1), train_data['Price']

reg = LinearRegression()
reg.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = reg.predict(X_test)

test_score = reg.score(X_test, y_test)
print(f"R-squared (Test Data): {test_score}")

mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

R-squared (Test Data): 0.23572143103480425
Mean Squared Error: 292534237638417.25

Exploring Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

RandomForestRegressor()

In [ ]:
rf.score(X_test, y_test)

0.28057122899700826